codemistic/General-Projects

- VirtualAssistant
A virtual assistant with Python. It's a general project if u can merge it , go for it...
> Created a VirtualAssistant

- car.py
> Car python

- C Project/LinkedList/14_LinkedListTraversal.c
- C Project/LinkedList/15_Linked_List_InsertAtFirst.c
- C Project/LinkedList/LinkedListDeletion/Delete_A_Node.c
- C Project/LinkedList/LinkedListDeletion/Delete_First.c
- C Project/LinkedList/LinkedListDeletion/Deleting_Last_Node.c
- C Project/LinkedList/LinkedListDeletion/Deletion_In_Between.c
- C Project/LinkedList/LinkedListDeletion/Linked_List_Traversal.c
- C Project/LinkedList/Linked_List_InsertAfterANode.c
- C Project/LinkedList/Linked_List_InsertAtEnd.c
- C Project/LinkedList/Linked_List_InsertInBetween.c
Added code for Linked List Insertion and Deletion In C including all the cases of both
> Added code for Linked List Insertion and Deletion In C

- Paint Application/paint.py
I have Tested the changes on local it works as described in the issue #6 
Please merge it under Hacktoberfest accepted Label
Required Libraires : PyQt5
Note: Do `pip i PyQt5`
> Changes as in #6 Python GUI Desktop Application

- Catch If You can (JS)/index.html
- Catch If You can (JS)/script.js
- Catch If You can (JS)/style.css
Made Catch If You can fun project using HTML, CSS, JS where every time when you hover over the box (div), the box will change the position.
It will help to understanding getBoundingClientRect() and addEventListener() method very easily.
> Added project

- C Project/Matrix Operation/MatrixOperation.c
Matrix operation using dynamically allocated matrix
> Create MatrixOperation.c project

- Text Editor/README.md
- Text Editor/TextEditor.py
Added Text Editor Project.py
Please merge it under `hacktoberfest`
> Added Text Editor Project.py

- Converters/NumberConverter.html
(fixed issue #68 )
Hi, i have add an html page to convert positive decimal numbers into other systems: hex, bin, octal, ternary. 
you can try this at local browser
> Number converter added

- PasswordGeneratorCli/gen.py
- PasswordGeneratorCli/help.txt
CLI Tool made using python to generate strong password. #32
I implemented strong password generator cli in python.
The password generation algorithm is based on various probability distributions available in random module of python.
The passwords generated aren't repeated until 10 million new passwords tested by creating frequency counter of passwords.
> add: password generator cli

- Guess-my-number/index.html
- Guess-my-number/script.js
- Guess-my-number/style.css
I have added a basic game base on JS, Please review it and guide me if any changes required
> Add: basic JS game added

- CONTRIBUTION.md
- code od conduct.md
Add code of conduct and contribution guides markdown files
required for hacktober fest
> Add code of conduct and contribution markdown files

- Number_plate_detection.py
This uses open cv2 and Haar cascade model
Please Merge.
Happy Hacktoberfest'22
#hacktoberfest
> Added Number Plate Detection Python script

- DataStructures/Linked-List-Operations.cpp
Hereby added, almost every fundamental operation in Linked List Data Structure in C++
> All operations in Linked List using CPP

- AudioBookReading
This code is For audiobookreading by python,
> AudioBookReading

- Data Analytics/Ecommerce Customer dataset .py
perform a data analysis to find should company focus on their mobile app or website to invest money using correlation
> Ecommerce Customers dataset

- currency converter.java
added currency converter project in java
> Created currency converter

- BMI Calculator.cpp
> Create BMI Calculator.cpp

- High_Low_Game/README.md
- High_Low_Game/high_low_game.py
This is my PR for Hacktoberfest 2022
> Added HighLowGame Project

- C Project/LinkedList/CircularLinkedList/CircularListTraversal.c
Added traversal of Circular Linked List
> Added Circular Linked List

- tkinter.py
> tkinter project

- DataStructures/circularQueue.cpp
This is a code representing the circular Queue data structure.
> Circular Queue structure

- Network Scanner/README.md
- Network Scanner/network_scanner.py
This is a python based command line Network Scanner utility, which takes input as an argument for the exact IP address or the relative IP Address range you wish to do the Network Scan for and returns all the available IP addresses with their MAC addresses on your current Network.
> Python based Network Scanner by Abhinandan Khurana

- TODO list app/README.md
- TODO list app/TODO app.yaml
A simple To-Do list web application (CRUD) made with Django using Anvil.
> To-Do List Web-Application

- find-s-algorithm/data.csv
- find-s-algorithm/data_testing.csv
- find-s-algorithm/finds.py
hi , i added some new project to this repo. pls kindly accept my PR. happy hacktoberfest :)
> add new project, find-s algorithm

- Python_Number-Guesser.py
It is basically one implementation of Python random module. Here using random module creating the number guesser game. Resulting the no. of times it takes for user to guess the correct one.
> Creating a new file named Python_Number-Guesser.py

- Cpp projects/LoginRegistrationSystem.cpp
Added Login Registration System including Profile and Setting page in C++.
> Added LoginRegistrationSystem

- Thankyou page/index.html
- Thankyou page/style.css
Thankyou page in Html, Css, JavaScript
It can be used in various projects
> Thankyou page

- ML-Projects/FakeNewsDetection.ipynb
Hey! Added this interesting ML project on Fake News Detection.
Please review it and accept the PR.
Requesting you to consider it for Hacktoberfest.
> Fake News Detection using Machine Learning

- DataStructures/Weight_of_Minimum_Spanning_Tree_using_Disjoin_Set_Union.cpp
This C++ code can be used to find the weight of the minimum spanning tree using DSU (Disjoint Set Union). 
Object Oriented code structure has been implemented.
> Added C++ code for finding the Weight of the Minimum Spanning Tree 

- Fast-clicker-game/index.html
Game based on HTML, CSS and JAVASCRIPT
> Added fast-clicker-game

- Etch-A-Sketch/app.js
- Etch-A-Sketch/index.html
- Etch-A-Sketch/style.css
A sketching game created using HTML5, CSS3 (the UI is responsive) and JavaScript.
> Added Etch-A-Sketch game

- NPM Searcher/.gitignore
- NPM Searcher/index.js
- NPM Searcher/package-lock.json
- NPM Searcher/package.json
> Add a simple program to search for npm packages

- DataStructures/matrix Chain Multiplication.cpp
Given the dimension of a sequence of matrices in an array arr[], where the dimension of the ith matrix is (arr[i-1] * arr[i]), the task is to find the most efficient way to multiply these matrices together such that the total number of element multiplications is minimum.
> Create matrix Chain Multiplication.cpp

- sudoko-solver-html/index.html
- sudoko-solver-html/script.js
- sudoko-solver-html/style.css
it solves #403
please add tag of hactoberfest  
thanks you
@gantavyamalviya
> sudoko-solver

- Calculator (beginner friendly to learn)/index.html
- Calculator (beginner friendly to learn)/script.js
- Calculator (beginner friendly to learn)/style.css
- Scrolled Percentage (JS)/index.html
- Scrolled Percentage (JS)/script.js
- Scrolled Percentage (JS)/style.css
Added impressive scrolling percent feature to make any website interactive.
> Added scrolled percentage feature

- Cpp projects/Encryption_Decryption.cpp
Encrypt your message with a key and use that key to Decrypt your same message.
> Adding Encryption and  Decryption project

- Catch Me If You Can/index.html
- Catch Me If You Can/script.js
- Catch Me If You Can/style.css
> Catch Me If You Can

- Five Digit Up Counter/index.html
- Five Digit Up Counter/script.js
- Five Digit Up Counter/style.css
> Five Digits Up Counter

- Blogs Website/app.js
- Blogs Website/package.json
I have added a project made by me using MongoDB, NodeJS, ExpressJS, and EJS. This is a Blogs website where u can create and view daily blogs.
> Added a Blog Project using MERN Stack

- Network Scanner/ARP Spoofer/README.md
- Network Scanner/ARP Spoofer/arp_spoofer.py
This is a Python based command line ARP Spoofer utility, which takes input as arguments for the exact target IP and gateway IP for which you wish to Spoof ARP request.
> ARP Spoofer - by Abhinandan Khurana

- Parking_system-project.cpp
@gantavyamalviya @Adarsh-jaiss  please verify my PR .
>  Parking_system-project.cpp

- allocate-till-end-of-memory/main.cpp
beginner friendly program to understand to how to Dynamic allocation of memory works in c++
> compsed memory Hungry program

- Tic_Tac_Toe_game/tic.cpp
A simple tic tac toe using cpp.
> Tic_Tac_Toe game

- Electron-whiteboard/Readme.md
- Electron-whiteboard/package-lock.json
- Electron-whiteboard/package.json
- Electron-whiteboard/src/index.css
- Electron-whiteboard/src/index.html
- Electron-whiteboard/src/index.js
Added a Electron js based whiteboard developed as a cross platform desktop application
> Electron based whiteboard desktop application

- How_Long_Command_Running/main.py
A simple command line application that lets you know how long your command has been running.
> How_long_command_running

- C Project/fibonacci.c
> A C program to generate Fibonacci sequence

- C Project/CycleStore Management System/main.c
Added a new C project-Cycle Store Management System Under the C Project Folder.
> Added a new C Project-Cycle Store Management System

- Python Basic Project/Huffman coding.py
Huffman coding is used to reduce the size of the give text file.
> A new project huffman coding added

- C Project/Hangman/hangman.c
- C Project/Interest Calculator/interest.c
Two programs have been added on their respective folder.
> Added two C programs - 'Hangman' and 'Interest Calculator'

- DataStructures/Tree.java
Pls review and merge my PR under Hacktoberfest 2022.
> Added Tree data structure

- BookShelf-Shifting-using-Linked-List.c
Shifting Books in a Book-Shelf to the terminal position from a desired location, Linked List used
> Create  BookShelf-Shifting-using-Linked-List.c

- Java Word Counter/WordCounter.java
Added a Java Project that counts number of word as well as characters in the entered text.
> Added a Java project-Word Counter

- Basic Calculator/index.css
- Basic Calculator/index.html
- Basic Calculator/script.js
Added Basic Calculator that is colorful which is made using HTML, CSS and JS.
> Basic Colorful Calculator

- Tic-Tac-Toe/code.cpp
Tic-Tac-toe Game in cpp need GCC to compile and run the application.
Please add the changes and make it accepted under `hacktoberfest`. Also Lable as `Hacktoberfest-accepted`.
@gantavyamalviya @Adarsh-jaiss
> Tic-Tac-Toe application.

- C Project/fibonacci.c
> Updates fibonacci.c

- Python Basic Project/Huffman coding.py
> Update Huffman coding.py

- Sentiment_Analysis.py
Created using python and its libraries named 'tweepy' and 'textblob'. Finds tweets related to one key word given and rates them from -1<x<1 scale.
> Created a 'Twitter Sentiment Analysis' script

- Theme Clock # 213
I creates a theme Analog clock with dark and light mode.
Added theme clock
> Create Theme Clock # 213

- Drunken_man_game/man.cpp
A simple game where a drunken man runs from start to finish.
> Drunken_man_Game

- Gaming Website Frontend/Readme.md
- Gaming Website Frontend/sprint.html
- Gaming Website Frontend/style.css
I have added 3 files in this pull request which contains code for Frontend of an Gaming Website.
> Added an project over frontend web development.

- client.py
- server.py
Created a two files named - 'Client.py' and 'Server.py' to implement basic socket principles.  Primarily using Python socket module and other libraries.
> Created a Python Socket Program.

- Billing-System/README.md
- Billing-System/billing_system.py
it uses python tkinter and generates a bill as per the data input by user
> Added Billing-System cum Bill-Generator

- car_race_game.cpp
> car_race_game

- TicTacToe Java Console Game/Board.java
- TicTacToe Java Console Game/Player.java
- TicTacToe Java Console Game/TicTacToe.java
It is fully functional and can be used to learn OOPS in JAVA programming language.
> Added java console game

- pointless-tic-tac-toe/index.html
- pointless-tic-tac-toe/script.js
- pointless-tic-tac-toe/style.css
Play against a tic tac toe AI where the best outcome you can achieve is a draw
> Pointless-tic-tac-toe

- Python Basic Project/guess_the_number.py
It is basic and very interesting pyhton program which should be added in the list
> guess the number project was added

- player.html
Please accept my request and add hacktoberfest label.
> Music Player

- invisibilitycloak.py
Please accept my request and add hacktoberfest label.
> Invisibility Cloak
